import PermanentalDominance.PSD
import Mathlib.LinearAlgebra.Matrix.SchurComplement

/-!
# Generic positive-semidefinite completion lemmas

This file contains the dimension-independent Schur-complement normalization
used to pass between a positive-definite principal block and the boundary of
its completion ellipsoid.
-/

noncomputable section

open Complex Matrix
open scoped ComplexOrder

namespace PermanentalDominance.Completion

/-- Regard a vector as a one-column matrix. -/
def column {n : Type*} (q : n → ℂ) : Matrix n (Fin 1) ℂ :=
  fun i _ => q i

/-- Rank-one matrix contributed by a completion column. -/
def rankOne {n : Type*} (q : n → ℂ) : Matrix n n ℂ :=
  fun i j => q i * star (q j)

/-- Schur residual of a unit final diagonal entry. -/
def residual {n : Type*} (B : Matrix n n ℂ) (q : n → ℂ) :
    Matrix n n ℂ :=
  B - rankOne q

private theorem column_mul_conjTranspose
    {n : Type*} [Fintype n] (q : n → ℂ) :
    column q * (column q)ᴴ = rankOne q := by
  ext i j
  simp [column, rankOne, Matrix.mul_apply, Fin.sum_univ_succ]

/-- The Schur residual of a PSD block completion with unit last diagonal is
PSD in every finite dimension. -/
theorem residual_posSemidef_of_fromBlocks
    {n : Type*} [Fintype n]
    {B : Matrix n n ℂ} {q : n → ℂ}
    (hA : (Matrix.fromBlocks B (column q) (column q)ᴴ
      (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef) :
    (residual B q).PosSemidef := by
  let Q := column q
  letI : Invertible (1 : Matrix (Fin 1) (Fin 1) ℂ) := invertibleOne
  have hschur := (Matrix.PosSemidef.fromBlocks₂₂
    B Q Matrix.PosDef.one).mp hA
  simpa [residual, Q, column_mul_conjTranspose] using hschur

/-- Diagonal matrix which divides a residual Gram vector by the nonzero
completion coordinates. -/
def inverseGauge {n : Type*} [DecidableEq n] (q : n → ℂ) :
    Matrix n n ℂ :=
  Matrix.diagonal fun i => (star (q i))⁻¹

/-- Residual Gram matrix in coordinates normalized by the completion column. -/
def normalizedResidual
    {n : Type*} [Fintype n] [DecidableEq n]
    (B : Matrix n n ℂ) (q : n → ℂ) : Matrix n n ℂ :=
  (inverseGauge q)ᴴ * residual B q * inverseGauge q

theorem normalizedResidual_posSemidef
    {n : Type*} [Fintype n] [DecidableEq n]
    {B : Matrix n n ℂ} {q : n → ℂ}
    (hR : (residual B q).PosSemidef) :
    (normalizedResidual B q).PosSemidef := by
  exact hR.conjTranspose_mul_mul_same (inverseGauge q)

/-- Entrywise form of the normalized residual.  This is the reusable bridge
from a block completion to scalar residual-Gram coordinates. -/
theorem normalizedResidual_apply
    {n : Type*} [Fintype n] [DecidableEq n]
    (B : Matrix n n ℂ) (q : n → ℂ) (i j : n)
    (hqi : q i ≠ 0) (hqj : q j ≠ 0) :
    normalizedResidual B q i j =
      B i j / (q i * star (q j)) - 1 := by
  rw [normalizedResidual, inverseGauge, Matrix.diagonal_conjTranspose]
  simp only [Matrix.mul_diagonal, Matrix.diagonal_mul, Function.comp_apply]
  simp [residual, rankOne, hqi, hqj, map_inv₀]
  field_simp [hqi, hqj]

/-- The block completion generated by a rank-one principal block is positive
semidefinite in every finite dimension. -/
theorem rankOne_fromBlocks_posSemidef
    {n : Type*} [Fintype n] (p : n → ℂ) :
    (Matrix.fromBlocks (rankOne p) (column p) (column p)ᴴ
      (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef := by
  letI : Invertible (1 : Matrix (Fin 1) (Fin 1) ℂ) := invertibleOne
  apply (Matrix.PosSemidef.fromBlocks₂₂
    (rankOne p) (column p) Matrix.PosDef.one).2
  simpa [column_mul_conjTranspose] using
    (Matrix.PosSemidef.zero :
      (0 : Matrix n n ℂ).PosSemidef)

/-- Convexly perturb a PSD unit block completion toward a rank-one
completion.  The new completion column is the same convex interpolation. -/
theorem convex_rankOne_fromBlocks_posSemidef
    {n : Type*} [Fintype n]
    {B : Matrix n n ℂ} {q : n → ℂ}
    (hA : (Matrix.fromBlocks B (column q) (column q)ᴴ
      (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef)
    (p : n → ℂ) {t : ℝ} (ht₀ : 0 ≤ t) (ht₁ : t ≤ 1) :
    (Matrix.fromBlocks
      (((1 - t : ℝ) : ℂ) • B + (t : ℂ) • rankOne p)
      (column fun i => (((1 - t : ℝ) : ℂ) * q i + (t : ℂ) * p i))
      (column fun i => (((1 - t : ℝ) : ℂ) * q i + (t : ℂ) * p i))ᴴ
      (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef := by
  have hP := rankOne_fromBlocks_posSemidef p
  have hsum :
      (((1 - t : ℝ) : ℂ) •
          Matrix.fromBlocks B (column q) (column q)ᴴ
            (1 : Matrix (Fin 1) (Fin 1) ℂ) +
        (t : ℂ) •
          Matrix.fromBlocks (rankOne p) (column p) (column p)ᴴ
            (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef :=
    (PermanentalDominance.IsPSD.nonneg_smul hA (sub_nonneg.mpr ht₁)).add
      (PermanentalDominance.IsPSD.nonneg_smul hP ht₀)
  convert hsum using 1
  ext i j
  cases i <;> cases j <;>
    simp [column, rankOne, map_add, map_mul]
  all_goals ring

/-- Adding a strictly positive scalar diagonal moves every positive-semidefinite
matrix into the positive-definite cone. -/
theorem add_posDiagonal_posDef
    {n : Type*} [Fintype n] [DecidableEq n]
    {B : Matrix n n ℂ} (hB : B.PosSemidef) {t : ℝ} (ht : 0 < t) :
    (B + (t : ℂ) • (1 : Matrix n n ℂ)).PosDef := by
  apply Matrix.PosDef.posSemidef_add hB
  rw [smul_one_eq_diagonal]
  apply Matrix.PosDef.diagonal
  intro i
  exact_mod_cast ht

/-- An injectively indexed principal submatrix of a positive-definite matrix
is positive definite. -/
theorem posDef_submatrix
    {n m : Type*} [Fintype n] [Fintype m]
    [DecidableEq n] [DecidableEq m]
    {B : Matrix n n ℂ} (hB : B.PosDef)
    (e : m → n) (he : Function.Injective e) :
    (B.submatrix e e).PosDef := by
  let S : Matrix n m ℂ := Matrix.submatrix 1 id e
  have hS : Function.Injective S.mulVec := by
    intro x y hxy
    ext i
    have hi := congr_fun hxy (e i)
    simpa [S, Matrix.mulVec, dotProduct, Matrix.one_apply, he.eq_iff] using hi
  have hpos : (Sᴴ * B * S).PosDef :=
    hB.conjTranspose_mul_mul_same hS
  have heq : Sᴴ * B * S = B.submatrix e e := by
    rw [show B = 1 * B * 1 by simp, Matrix.submatrix_mul
        (he₂ := Function.bijective_id), Matrix.submatrix_mul
        (he₂ := Function.bijective_id), Matrix.submatrix_id_id]
    simp only [S, Matrix.conjTranspose_submatrix, Matrix.conjTranspose_one]
    simp
  rw [← heq]
  exact hpos

/-- A positive-semidefinite matrix with positive determinant is positive
definite. -/
theorem posDef_of_posSemidef_det_pos
    {n : Type*} [Fintype n] [DecidableEq n]
    {B : Matrix n n ℂ} (hB : B.PosSemidef) (hdet : 0 < B.det) :
    B.PosDef := by
  refine ⟨hB.1, ?_⟩
  intro x hx
  have hq : 0 ≤ dotProduct (star x) (B *ᵥ x) := hB.2 x
  have hne : dotProduct (star x) (B *ᵥ x) ≠ 0 := by
    intro hz
    have hBx : B *ᵥ x = 0 := hB.dotProduct_mulVec_zero_iff x |>.mp hz
    have hx0 : x = 0 := Matrix.eq_zero_of_mulVec_eq_zero hdet.ne' hBx
    exact hx hx0
  exact lt_of_le_of_ne hq (Ne.symm hne)

private theorem scaled_quadratic
    {n : Type*} [Fintype n] (A : Matrix n n ℂ)
    (y : n → ℂ) (alpha : ℂ) :
    dotProduct (star (alpha • y)) (A *ᵥ (alpha • y)) =
      star alpha * alpha * dotProduct (star y) (A *ᵥ y) := by
  rw [Matrix.mulVec_smul, StarModule.star_smul,
    smul_dotProduct, dotProduct_smul]
  simp only [smul_eq_mul]
  ring

private theorem column_quadratic
    {n : Type*} [Fintype n] (A : Matrix n n ℂ) (q : n → ℂ) :
    (column q)ᴴ * A * column q =
      fun _ _ => dotProduct (star q) (A *ᵥ q) := by
  ext i j
  fin_cases i
  fin_cases j
  simp only [column, Matrix.conjTranspose_apply, starRingEnd_apply,
    Matrix.mul_apply, dotProduct, Matrix.mulVec, Finset.sum_mul]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro i _
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j _
  ac_rfl

/-- Normalizing a nonzero vector by its inverse quadratic norm gives a PSD
rank-one completion with unit final diagonal. -/
theorem normalized_fromBlocks_posSemidef
    {n : Type*} [Fintype n] [DecidableEq n]
    {B : Matrix n n ℂ} (hB : B.PosDef) (y : n → ℂ) (hy : y ≠ 0) :
    let rho := dotProduct (star y) (B⁻¹ *ᵥ y)
    let r := rho.re
    let q : n → ℂ := ((Real.sqrt r : ℂ)⁻¹) • y
    (Matrix.fromBlocks B (column q) (column q)ᴴ
      (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef := by
  dsimp only
  let _ : Invertible B := hB.isUnit.invertible
  let rho : ℂ := dotProduct (star y) (B⁻¹ *ᵥ y)
  let r : ℝ := rho.re
  have hrho : 0 < rho := hB.inv.2 y hy
  have hr : 0 < r := (RCLike.pos_iff.mp hrho).1
  have hrho_cast : (r : ℂ) = rho := by
    apply Complex.ext
    · rfl
    · simpa [r] using (RCLike.pos_iff.mp hrho).2.symm
  let alpha : ℂ := (Real.sqrt r : ℂ)⁻¹
  let q : n → ℂ := alpha • y
  let Q : Matrix n (Fin 1) ℂ := column q
  have hsqrtC : (Real.sqrt r : ℂ) ^ 2 = (r : ℂ) := by
    exact_mod_cast Real.sq_sqrt hr.le
  have halpha : star alpha * alpha = (r : ℂ)⁻¹ := by
    have hsqrt0 : (Real.sqrt r : ℂ) ≠ 0 := by
      exact_mod_cast Real.sqrt_ne_zero'.mpr hr
    have hr0 : (r : ℂ) ≠ 0 := by exact_mod_cast hr.ne'
    dsimp [alpha]
    rw [map_inv₀]
    simp only [Complex.star_def, map_ofNat, conj_ofReal]
    field_simp [hsqrt0, hr0]
    simpa [pow_two] using hsqrtC.symm
  have hqform : dotProduct (star q) (B⁻¹ *ᵥ q) = 1 := by
    rw [show q = alpha • y by rfl, scaled_quadratic, halpha]
    change (r : ℂ)⁻¹ * rho = 1
    rw [← hrho_cast]
    field_simp [hr.ne']
  have hschur :
      (1 : Matrix (Fin 1) (Fin 1) ℂ) - Qᴴ * B⁻¹ * Q = 0 := by
    rw [show Q = column q by rfl, column_quadratic]
    ext i j
    fin_cases i
    fin_cases j
    simp [hqform]
  apply (Matrix.PosSemidef.fromBlocks₁₁ Q
    (1 : Matrix (Fin 1) (Fin 1) ℂ) hB).2
  rw [hschur]
  exact Matrix.PosSemidef.zero

/-- If an affine Hermitian quadratic is nonnegative on every unit block
completion of a positive-semidefinite matrix, then its adjugate certificate is
positive semidefinite.  This is the dimension-independent ellipsoid argument
behind the geometric certificates. -/
theorem ellipsoidCertificate_posSemidef
    {n : Type*} [Fintype n] [DecidableEq n]
    {B K : Matrix n n ℂ} {c : ℝ}
    (hB : B.PosSemidef) (hK : K.IsHermitian)
    (hellipsoid : ∀ q : n → ℂ,
      (Matrix.fromBlocks B (column q) (column q)ᴴ
        (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef →
      0 ≤ c + (dotProduct (star q) (K *ᵥ q)).re) :
    (B.det • K + (c : ℂ) • B.adjugate).PosSemidef := by
  have hdet₀ : 0 ≤ B.det :=
    PermanentalDominance.IsPSD.det_nonneg hB
  by_cases hdetZero : B.det = 0
  · have hblockZero :
        (Matrix.fromBlocks B (column (0 : n → ℂ))
          (column (0 : n → ℂ))ᴴ
          (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef := by
      letI : Invertible (1 : Matrix (Fin 1) (Fin 1) ℂ) := invertibleOne
      apply (Matrix.PosSemidef.fromBlocks₂₂ B
        (column (0 : n → ℂ)) Matrix.PosDef.one).2
      have hcolumnZero : column (0 : n → ℂ) = 0 := by
        ext i j
        simp [column]
      simpa [hcolumnZero] using hB
    have hc : 0 ≤ c := by
      simpa using hellipsoid 0 hblockZero
    rw [hdetZero, zero_smul, zero_add]
    exact PermanentalDominance.IsPSD.nonneg_smul
      (PermanentalDominance.IsPSD.adjugate hB) hc
  · have hdet : 0 < B.det := lt_of_le_of_ne hdet₀ (Ne.symm hdetZero)
    have hBpd : B.PosDef := posDef_of_posSemidef_det_pos hB hdet
    let _ : Invertible B := hBpd.isUnit.invertible
    have hBinvHermitian : B⁻¹.IsHermitian := hBpd.inv.isHermitian
    have hformHermitian : (K + (c : ℂ) • B⁻¹).IsHermitian := by
      rw [Matrix.IsHermitian]
      simp only [Matrix.conjTranspose_add, Matrix.conjTranspose_smul]
      rw [hK.eq, hBinvHermitian.eq]
      simp
    have hform : (K + (c : ℂ) • B⁻¹).PosSemidef := by
      apply PermanentalDominance.IsPSD.of_re_dotProduct_nonneg hformHermitian
      intro y
      by_cases hy : y = 0
      · subst y
        simp
      · let rho : ℂ := dotProduct (star y) (B⁻¹ *ᵥ y)
        let r : ℝ := rho.re
        have hrho : 0 < rho := hBpd.inv.2 y hy
        have hr : 0 < r := (RCLike.pos_iff.mp hrho).1
        let q : n → ℂ := ((Real.sqrt r : ℂ)⁻¹) • y
        have hcompletion :
            (Matrix.fromBlocks B (column q) (column q)ᴴ
              (1 : Matrix (Fin 1) (Fin 1) ℂ)).PosSemidef := by
          simpa [rho, r, q] using
            normalized_fromBlocks_posSemidef hBpd y hy
        have hgap := hellipsoid q hcompletion
        have hsqrt : (Real.sqrt r) ^ 2 = r := Real.sq_sqrt hr.le
        have hquad :
            (dotProduct (star q) (K *ᵥ q)).re =
              r⁻¹ * (dotProduct (star y) (K *ᵥ y)).re := by
          rw [show q = ((Real.sqrt r : ℂ)⁻¹) • y by rfl,
            scaled_quadratic]
          have hsqrt₀ : Real.sqrt r ≠ 0 := Real.sqrt_ne_zero'.mpr hr
          norm_num [Complex.mul_re, Complex.inv_re, Complex.inv_im]
          field_simp [hsqrt₀, hsqrt, hr.ne']
        rw [hquad] at hgap
        have hscaled := mul_nonneg hr.le hgap
        have hscaled' :
            0 ≤ (dotProduct (star y) (K *ᵥ y)).re + c * r := by
          have heq :
              r * (c + r⁻¹ * (dotProduct (star y) (K *ᵥ y)).re) =
                (dotProduct (star y) (K *ᵥ y)).re + c * r := by
            field_simp [hr.ne']
            ring
          rw [heq] at hscaled
          exact hscaled
        have hformValue :
            (dotProduct (star y)
              ((K + (c : ℂ) • B⁻¹) *ᵥ y)).re =
              (dotProduct (star y) (K *ᵥ y)).re + c * r := by
          simp only [Matrix.add_mulVec, Matrix.smul_mulVec_assoc,
            dotProduct_add, dotProduct_smul, Complex.add_re,
            Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im,
            zero_mul, sub_zero, smul_eq_mul]
          rw [show (dotProduct (star y) (B⁻¹ *ᵥ y)).re = r by rfl]
        rw [hformValue]
        exact hscaled'
    have hadj : B.adjugate = B.det • B⁻¹ := by
      have hBunit : IsUnit B.det :=
        isUnit_iff_ne_zero.mpr hdet.ne'
      calc
        B.adjugate = 1 * B.adjugate := by rw [Matrix.one_mul]
        _ = (B⁻¹ * B) * B.adjugate := by
          rw [Matrix.nonsing_inv_mul B hBunit]
        _ = B⁻¹ * (B * B.adjugate) := by rw [Matrix.mul_assoc]
        _ = B⁻¹ * (B.det • (1 : Matrix n n ℂ)) := by
          rw [Matrix.mul_adjugate]
        _ = B.det • B⁻¹ := by rw [Matrix.mul_smul, Matrix.mul_one]
    have hcertificate :
        B.det • K + (c : ℂ) • B.adjugate =
          B.det • (K + (c : ℂ) • B⁻¹) := by
      rw [hadj]
      module
    rw [hcertificate]
    have hdetCast : (B.det.re : ℂ) = B.det := by
      apply Complex.ext
      · rfl
      · simpa using (RCLike.pos_iff.mp hdet).2.symm
    rw [← hdetCast]
    exact PermanentalDominance.IsPSD.nonneg_smul hform
      (RCLike.pos_iff.mp hdet).1.le

end PermanentalDominance.Completion
